# Node Name: handover_controller
handover_controller:

  ros__parameters:

    # UR5e Parameters
    payload: 12.50 # kg
    reach: 1.30 # m
    max_speed: 120.0 # deg/s
    stopping_time: 0.150 # s
    stopping_distance: 0.25 # m
    position_uncertainty: 0.05 # mm
